services:
  react-news-bot:
    build: .
    container_name: react-news-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5001:5001"
    volumes:
      - /home/pentagon-admin/Documents/apps/obsidian-vaults/frontend/raw/twir:/app/data
